_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  META_ARCHITECTURE: "VGT"
  WORDGRID:
    VOCAB_SIZE: 250005
    EMBEDDING_DIM: 64
    MODEL_PATH: "/kaggle/working/vgt/object_detection/path/xlm-roberta-uncased/"
    USE_PRETRAIN_WEIGHT: True
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  BACKBONE:
    NAME: "build_VGT_fpn_backbone"
  WEIGHTS: "/kaggle/input/doclaynet_9k_20241007/pytorch/default/2/model_final.pth"
  VIT:
    NAME: "VGT_dit_base_patch16"
    MERGE_TYPE: "Sum"
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 10
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  BASE_LR: 0.0001
  WARMUP_ITERS: 500
  IMS_PER_BATCH: 4
  MAX_ITER: 20000
  STEPS: (15000, 17500)
  CHECKPOINT_PERIOD: 2500
  # CHECKPOINT_PERIOD: 200
TEST:
  # EVAL_PERIOD: 200
  EVAL_PERIOD: 2500
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST: ("doclaynet_val",)
  
  
