_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  META_ARCHITECTURE: "VGT"
  WORDGRID:
    VOCAB_SIZE: 30552
    EMBEDDING_DIM: 64
    MODEL_PATH: "./path/xlm-roberta-uncased/"
    USE_PRETRAIN_WEIGHT: True
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  BACKBONE:
    NAME: "build_VGT_fpn_backbone"
  WEIGHTS: "/kaggle/input/checkpoint/model_final.pth"
  VIT:
    NAME: "VGT_dit_base_patch16"
    MERGE_TYPE: "Sum"
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  BASE_LR: 0.0002
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 4
  MAX_ITER: 28000
  STEPS: (20000, 24000)
TEST:
  EVAL_PERIOD: 4000
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST: ("doclaynet_val",)
  
  
