_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  META_ARCHITECTURE: "VGT"
  WORDGRID:
    VOCAB_SIZE: 250005
    EMBEDDING_DIM: 64
    MODEL_PATH: "./path/xlm-roberta-uncased/"
    USE_PRETRAIN_WEIGHT: True
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  BACKBONE:
    NAME: "build_VGT_fpn_backbone"
  WEIGHTS: "./model_0019999.pth"
  VIT:
    NAME: "VGT_dit_base_patch16"
    MERGE_TYPE: "Sum"
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 5
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  BASE_LR: 0.00005
  WARMUP_ITERS: 2000
  STEPS: (10000, 20000)
  MAX_ITER: 20000
  IMS_PER_BATCH: 2
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ("publaynet_train",)
  TEST: ("publaynet_val",)